question_data = [
    {
        "type": "boolean", "difficulty": "hard", "category": "History",
        "question": "The USS Missouri (BB-63) last served in the Korean War.",
        "correct_answer": "False", "incorrect_answers": ["True"]
    },
    {
        "type": "boolean", "difficulty": "hard",
        "category": "Science &amp; Nature",
        "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
        "correct_answer": "True", "incorrect_answers": ["False"]
    },
    {
        "type": "boolean", "difficulty": "hard",
        "category": "Entertainment: Video Games",
        "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man&#039;s Tree.",
        "correct_answer": "True", "incorrect_answers": ["False"]
    },
    {
        "type": "boolean", "difficulty": "hard",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "The protagonist in &quot;Humanity Has Declined&quot; has no discernable name and is simply referred to as &#039;I&#039; for most of the series.",
        "correct_answer": "True", "incorrect_answers": ["False"]
    },
    {
        "type": "boolean", "difficulty": "hard", "category": "Mythology",
        "question": "Janus was the Roman god of doorways and passageways.",
        "correct_answer": "True", "incorrect_answers": ["False"]
    },
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "In Undertale, having a &quot;Fun Value&quot; set to 56-57 will play the &quot;Wrong Number Song Call&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Vehicles",
     "question": "The term &quot;GTO&quot; was originated by Ferrari?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science &amp; Nature",
     "question": "The value of one Calorie is different than the value of one calorie.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Politics",
     "question": "Joko Widodo has appeared in the cover of a TIME magazine.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Film",
     "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The Battle of Trafalgar took place on October 23rd, 1805",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Board Games",
     "question": "The board game Go has more possible legal positions than the number of atoms in the visible universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science: Computers",
     "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "TF2: Sentry rocket damage falloff is calculated based on the distance between the sentry and the enemy, not the engineer and the enemy",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science &amp; Nature",
     "question": "The chemical element Lithium is named after the country of Lithuania.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Music",
     "question": "The song Scatman&#039;s World was released after Scatman (Ski-Ba-Bop-Ba-Dop-Bop).",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In the &quot;Kagerou Daze&quot; series, Shintaro Kisaragi is prominently shown with the color red.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "In &quot;Minecraft&quot;, gold tools are faster than diamond tools.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Musicals &amp; Theatres",
     "question": "The protagonist&#039;s names in &#039;Who&#039;s Afraid of Virginia Woolf&#039;, George and Martha, were derived from George Washington and his wife.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The man that shot Alexander Hamilton was named Aaron Burr.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "General Knowledge",
     "question": "Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Music",
     "question": "The song &quot;Mystery Train&quot; was released by artist &quot;Little Junior&#039;s Blue Flames&quot; in 1953.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The Kingdom of Prussia briefly held land in Estonia.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science: Mathematics",
     "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the distance from the Earth to the Sun.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "The Paradox Interactive game &quot;Stellaris&quot; was released in 2016.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Vehicles",
     "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "In &quot;The Sims&quot; series, the most members in a household you can have is 8.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Television",
     "question": "The Klingon home planet is Qo&#039;noS.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Geography",
     "question": "Only one country in the world starts with the letter Q.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Geography",
     "question": "Switzerland has four national languages, English being one of them.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The fourth funnel of the RMS Titanic was fake designed to make the ship look more powerful and symmetrical.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Music",
     "question": "The band STRFKR was also briefly known as Pyramiddd.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science: Mathematics",
     "question": "The binary number &quot;101001101&quot; is equivalent to the Decimal number &quot;334&quot;",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "General Knowledge",
     "question": "NCIS stands for &quot;Navy Corps Investigative Service&quot;",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Politics",
     "question": "Nazi Germany surrendered on Harry Truman&#039;s birthday while he was president.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science: Computers",
     "question": "DHCP stands for Dynamic Host Configuration Port.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Comics",
     "question": "In the comic book &quot;Archie&quot;, Betty is friends with Veronica because she is rich.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Mythology",
     "question": "Rannamaari was a sea demon that haunted the people of the Maldives and had to be appeased monthly with the sacrifice of a virgin girl.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Politics",
     "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science: Computers",
     "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science: Mathematics",
     "question": "In Topology, the complement of an open set is a closed set.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Druid is a mage class in &quot;Log Horizon&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Celebrities",
     "question": "Lady Gaga&#039;s real name is Stefani Joanne Angelina Germanotta.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Film",
     "question": "&quot;Cube&quot;, &quot;Cube 2: Hypercube&quot; and &quot;Cube Zero&quot; were directed by the same person.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Science: Mathematics",
     "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "The video game &quot;Fuel&quot; has an open world that is 5,560 square miles?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard",
     "category": "General Knowledge",
     "question": "&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
